### ISSUE TITLE
Appears to be dependent on react-native.

### ISSUE THREAD

**Issue by hally9k** [stermedia/react-web-gifted-chat#1]
#### Issue Description

Webpack can't build as it looks for react-native

#### Steps to Reproduce / Code Snippets

Add to a project and build with webpack 3 and babel 6

#### Expected Results

Errr, works?

#### Additional Information

* React Native version: Ummm the web so none?
* react-native-gifted-chat version: react-web-gifted-chat
* Platform(s) (iOS, Android, or both?): um chrome.

**Comment by Frexuz** [comment]
Same.. We really would love to use this :D Already using in RN <3

**Comment by Nandez89** [comment]
Any updates on this issue? Currently looking for a similar solution like this already using the one for RN but in need to create a web chat widget similar to [the one by facebook](https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin)

**Comment by lineldcosta** [comment]
Same Issue..

**Comment by everscending** [comment]
I'm having the same issue.  Has anyone gotten this package to work successfully?

**Comment by johniak** [comment]
Sorry again, in the next upgrade it will be working, I also fixed example, this is already on repository, but it's not pushed to npm, it also contains new react version

**Comment by KyruCabading** [comment]
This issue still exists for me, trying to get it to work with NextJS. I've followed adding the right alias resolvers through babelrc & NextJS config but still doesn't work. 

react-native-web components work fine though.
`{ Error: Cannot find module 'react-native'`

**Comment by bibek-magar** [comment]
Any updates?
